export const BASE_URL = 'http://192.168.1.3:3000'
export const actionStories = {
    FETCH_STORIES_REQUEST: 'FETCH_STORIES_REQUEST',
    FETCH_STORIES_FAILURE: 'FETCH_STORIES_FAILURE',
    FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS'
}
export const postsActions = {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS'
}
export const friendActions = {
    FETCH_RECOMMAND_FRIENDS_REQUEST: 'FETCH_RECOMMAND_FRIENDS_REQUEST',
    FETCH_RECOMMAND_FRIENDS_FAILURE: 'FETCH_RECOMMAND_FRIENDS_FAILURE',
    FETCH_RECOMMAND_FRIENDS_SUCCESS: 'FETCH_RECOMMAND_FRIENDS_SUCCESS'
}
export const userActions = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
}
export const bgColorsActions = {
    FETCH_BGCOLORS_REQUEST: 'FETCH_BGCOLORS_REQUEST',
    FETCH_BGCOLORS_FAILURE: 'FETCH_BGCOLORS_FAILURE',
    FETCH_BGCOLORS_SUCCESS: 'FETCH_BGCOLORS_SUCCESS'
}
export const postDetailActions = {
    FETCH_POST_DETAIL_REQUEST: 'FETCH_POST_DETAIL_REQUEST',
    FETCH_POST_DETAIL_FAILURE: 'FETCH_POST_DETAIL_FAILURE',
    FETCH_POST_DETAIL_SUCCESS: 'FETCH_POST_DETAIL_SUCCESS',
    CLOSE_POST_DETAIL_MODAL: 'CLOSE_POST_DETAIL_MODAL',
    OPEN_COMMENTS_MODAL: 'OPEN_COMMENTS_MODAL',
    CLOSE_COMMENTS_MODAL: 'CLOSE_COMMENTS_MODAL'
}
export const showingStoryActions = {
    SET_SHOWING_STORY_REQUEST: 'SET_SHOWING_STORY_REQUEST',
    SET_SHOWING_STORY: 'SET_SHOWING_STORY',
    SET_VIEWED_STORY_REQUEST: 'SET_VIEWED_STORY_REQUEST',
    SET_VIEWED_STORY_FAILURE: 'SET_VIEWED_STORY_FAILURE',
    SET_VIEWED_STORY_SUCCESS: 'SET_VIEWED_STORY_SUCCESS',
}
export const FIXED_STATUSBAR_HEIGHT = 44