import { Dimensions } from 'react-native'
export const SCREEN_HEIGHT = Math.round(Dimensions.get('window').height);
export const SCREEN_WIDTH = Math.round(Dimensions.get('window').width);
export const BASE_URL = 'http://192.168.1.3:3000'
export const permission = {
    PUBLIC: 1,
    GROUP: 2,
    SETTING: 3
}
export const actionStories = {
    FETCH_STORIES_REQUEST: 'FETCH_STORIES_REQUEST',
    FETCH_STORIES_FAILURE: 'FETCH_STORIES_FAILURE',
    FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS'
}
export const watchSearchRecommandActions = {
    FETCH_WATCH_SEARCH_RECOMMANDS_REQUEST: 'FETCH_WATCH_SEARCH_RECOMMANDS_REQUEST',
    FETCH_WATCH_SEARCH_RECOMMANDS_FAILURE: 'FETCH_WATCH_SEARCH_RECOMMANDS_FAILURE',
    FETCH_WATCH_SEARCH_RECOMMANDS_SUCCESS: 'FETCH_WATCH_SEARCH_RECOMMANDS_SUCCESS'
}
export const videoControlActions = {
    RESET_WATCHING_STATUS: 'RESET_WATCHING_STATUS',
    SET_WATCHING_VIDEO: 'SET_WATCHING_VIDEO',
    SET_FIXED_HEIGH_WATCHING_VIDEO: 'SET_FIXED_HEIGH_WATCHING_VIDEO',
}
export const watchVidesActions = {
    FETCH_WATCH_VIDEOS_REQUEST: 'FETCH_WATCH_VIDEOS_REQUEST',
    FETCH_WATCH_VIDEOS_FAILURE: 'FETCH_WATCH_VIDEOS_FAILURE',
    FETCH_WATCH_VIDEOS_SUCCESS: 'FETCH_WATCH_VIDEOS_SUCCESS',
    FETCH_SEEN_WATCH_VIDEOS_REQUEST: 'FETCH_SEEN_WATCH_VIDEOS_REQUEST',
    FETCH_SEEN_WATCH_VIDEOS_FAILURE: 'FETCH_SEEN_WATCH_VIDEOS_FAILURE',
    FETCH_SEEN_WATCH_VIDEOS_SUCCESS: 'FETCH_SEEN_WATCH_VIDEOS_SUCCESS'
}
export const groupCategoriesActions = {
    FETCH_GROUP_CATEGORIES_REQUEST: 'FETCH_GROUP_CATEGORIES_REQUEST',
    FETCH_GROUP_CATEGORIES_FAILURE: 'FETCH_GROUP_CATEGORIES_FAILURE',
    FETCH_GROUP_CATEGORIES_SUCCESS: 'FETCH_GROUP_CATEGORIES_SUCCESS'
}
export const groupDetailActions = {
    FETCH_GROUP_DETAIL_REQUEST: 'FETCH_GROUP_DETAIL_REQUEST',
    FETCH_GROUP_DETAIL_FAILURE: 'FETCH_GROUP_DETAIL_FAILURE',
    FETCH_GROUP_DETAIL_SUCCESS: 'FETCH_GROUP_DETAIL_SUCCESS'
}
export const categoryGroupListActions = {
    FETCH_CATEGORY_GROUPS_REQUEST: 'FETCH_CATEGORY_GROUPS_REQUEST',
    FETCH_CATEGORY_GROUPS_FAILURE: 'FETCH_CATEGORY_GROUPS_FAILURE',
    FETCH_CATEGORY_GROUPS_SUCCESS: 'FETCH_CATEGORY_GROUPS_SUCCESS'
}
export const historyActions = {
    FETCH_GROUP_HISTOIES_REQUEST: 'FETCH_GROUP_HISTOIES_REQUEST',
    FETCH_GROUP_HISTOIES_FAILURE: 'FETCH_GROUP_HISTOIES_FAILURE',
    FETCH_GROUP_HISTOIES_SUCCESS: 'FETCH_GROUP_HISTOIES_SUCCESS'
}
export const postsActions = {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS'
}
export const systemImagesActions = {
    FETCH_SYSTEM_IMAGES_REQUEST: 'FETCH_SYSTEM_IMAGES_REQUEST',
    FETCH_SYSTEM_IMAGES_FAILURE: 'FETCH_SYSTEM_IMAGES_FAILURE',
    FETCH_SYSTEM_IMAGES_SUCCESS: 'FETCH_SYSTEM_IMAGES_SUCCESS'
}
export const groupPostsActions = {
    FETCH_GROUP_POSTS_REQUEST: 'FETCH_GROUP_POSTS_REQUEST',
    FETCH_GROUP_POSTS_FAILURE: 'FETCH_GROUP_POSTS_FAILURE',
    FETCH_ALLGROUP_POSTS_SUCCESS: 'FETCH_ALLGROUP_POSTS_SUCCESS',
    FETCH_INGROUP_POSTS_SUCCESS: 'FETCH_INGROUP_POSTS_SUCCESS'
}
export const groupActions = {
    FETCH_GROUPS_REQUEST: 'FETCH_GROUPS_REQUEST',
    FETCH_GROUPS_FAILURE: 'FETCH_GROUPS_FAILURE',
    FETCH_GROUPS_SUCCESS: 'FETCH_GROUPS_SUCCESS'
}
export const friendActions = {
    FETCH_RECOMMAND_FRIENDS_REQUEST: 'FETCH_RECOMMAND_FRIENDS_REQUEST',
    FETCH_RECOMMAND_FRIENDS_FAILURE: 'FETCH_RECOMMAND_FRIENDS_FAILURE',
    FETCH_RECOMMAND_FRIENDS_SUCCESS: 'FETCH_RECOMMAND_FRIENDS_SUCCESS'
}
export const userActions = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
}
export const bgColorsActions = {
    FETCH_BGCOLORS_REQUEST: 'FETCH_BGCOLORS_REQUEST',
    FETCH_BGCOLORS_FAILURE: 'FETCH_BGCOLORS_FAILURE',
    FETCH_BGCOLORS_SUCCESS: 'FETCH_BGCOLORS_SUCCESS'
}
export const postDetailActions = {
    FETCH_POST_DETAIL_REQUEST: 'FETCH_POST_DETAIL_REQUEST',
    FETCH_POST_DETAIL_FAILURE: 'FETCH_POST_DETAIL_FAILURE',
    FETCH_POST_DETAIL_SUCCESS: 'FETCH_POST_DETAIL_SUCCESS',
    CLOSE_POST_DETAIL_MODAL: 'CLOSE_POST_DETAIL_MODAL',
    OPEN_COMMENTS_MODAL: 'OPEN_COMMENTS_MODAL',
    CLOSE_COMMENTS_MODAL: 'CLOSE_COMMENTS_MODAL'
}
export const showingStoryActions = {
    SET_SHOWING_STORY_REQUEST: 'SET_SHOWING_STORY_REQUEST',
    SET_SHOWING_STORY: 'SET_SHOWING_STORY',
    SET_VIEWED_STORY_REQUEST: 'SET_VIEWED_STORY_REQUEST',
    SET_VIEWED_STORY_FAILURE: 'SET_VIEWED_STORY_FAILURE',
    SET_VIEWED_STORY_SUCCESS: 'SET_VIEWED_STORY_SUCCESS',
}
export const FIXED_STATUSBAR_HEIGHT = 44